### ISSUE TITLE
saves problems and languages problems

### ISSUE THREAD

**Issue by djsolidsnake86** [Ashok0/HL2VREssentials#10]
i encountered in a save problem where can't load a save
only if i start a level from zero the game start
if i load any save the game stuck in loading screen
any solutions? 

also there are problems with languages, game with mods start in english sometimes, but where i start the normal vr with this mod it start always in my language

**Comment by Ashok0** [comment]
This may be from an incorrect setting in MO2.  Under Tools > Settings > Workarounds, the Steam App ID needs to be changed from 220 to 658920.  This problem has been fixed with v1.0 of the Repack.  Closing this issue for now, feel free to open a new ticket if these issues persist with the new release.
