### ISSUE TITLE
Controllers appear to be disabled

### ISSUE THREAD

**Issue by hobyvh** [Ashok0/HL2VREssentials#16]
After discarding the previous release and installing the new release, MO2 appeared to be loading as intended. Conflicts were showing beside most mods but I was able to Run without error. Launching the game, I found I was unable to interact with the game menu in VR.

I then went to my mouse and keyboard to load a saved game. When that loaded I found that the graphics were indeed looking different but nothing worked with my controllers—movement or buttons. Looking down, I could see Gordon's gloves laying close together on the ground. Nothing I did with the controllers could get them moving. I took off my headset and quit with the mouse and keyboard.

**Comment by Ashok0** [comment]
That's strange, I haven't seen this problem before.  Do your controllers work if you disable all mods in MO2 before running the game?  Or do you get any different behavior when starting a new game versus loading a saved game?

Also if you launch the game with the console active, the main menu won't work in your VR headset.  To use the main menu in VR with your controllers, launch the game with "Half-Life 2 VR" selected in the upper right drop down bar instead of "Half-Life 2 VR (Console)".

**Comment by Ashok0** [comment]
One thing you might want to try is making sure your controllers are active before launching the game.  Let me know if this helps, thus far I have been unable to reproduce this problem.

**Comment by hobyvh** [comment]
1. Controllers active - it must have been this, since this time I was able to use the in-game menu with the controllers.
2. New Game instead of saved game - I did try this as well, everything loaded okay.
3. No mods activated - I didn't bother trying this, since the controllers were already working with 1 and 2.
